# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UiPathPack-preview@5
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    orchestratorConnection: 'DevOps'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy-preview@5
  inputs:
    orchestratorConnection: 'DevOps'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Qdev'
    processName: 'Modules'